#define DEFAULT_RU 0
#define DEFAULT_ACE_RU 0
#define DEFAULT_INS 0
#define DEFAULT_GUE 0
#define DEFAULT_BIS_TK 1
#define DEFAULT_BIS_TK_INS 1
#define DEFAULT_BIS_TK_GUE 0
#define DEFAULT_CWR2_US 0
#define DEFAULT_CWR2_RU 0
#define DEFAULT_CWR2_FIA 0
#define DEFAULT_tigerianne 0
#define DEFAULT_ibr_arl_faction 0
#define DEFAULT_ibr_drg_faction 0
#define DEFAULT_ibr_unisol_faction 0
#define DEFAULT_ibr_venator_faction 0
#define DEFAULT_ibr_police_unit 0
#define DEFAULT_LIN_army 0
#define DEFAULT_NLA 0
#define DEFAULT_MOL_army 0
#define DEFAULT_ibr_rebel_faction 0
